name: Create Release with Tag Name

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Tag Name
        id: tag_name
        run: echo "::set-output name=name::$(basename ${{ github.ref }})"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_name.outputs.name }}
          title: ${{ steps.tag_name.outputs.name }}
          
